name: my_finance_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  auto_route: ^7.8.4
  flutter_svg: ^2.0.9
  flutter_bloc: ^8.1.3
  get_it: ^7.6.4
  smooth_page_indicator: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.2
  pie_chart: ^5.4.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^7.1.1
  build_runner: ^2.4.4

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/onboarding/
    - assets/images/tab-icons/
    - assets/images/elements/
    - assets/images/profile/
    - assets/images/news/


  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
        - asset: fonts/Inter-Medium.ttf
        - asset: fonts/Inter-Bold.ttf
        - asset: fonts/Inter-Black.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"